-- You can reference from https://joke00.tistory.com/176
UPDATE SYS.PROPS$ SET VALUE$='KO16MSWIN949' WHERE NAME='NLS_CHARACTERSET';
UPDATE SYS.PROPS$ SET VALUE$='KO16MSWIN949' WHERE NAME='NLS_NCHAR_CHARACTERSET';
UPDATE SYS.PROPS$ SET VALUE$='KOREAN_KOREA.KO16MSWIN949' WHERE NAME='NLS_LANGUAGE';
COMMIT;

SHUTDOWN IMMEDIATE;

STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER DATABASE OPEN;
ALTER DATABASE CHARACTER SET INTERNAL_USE KO16MSWIN949;
SHUTDOWN IMMEDIATE;

STARTUP;

-- You can reference from https://m.blog.naver.com/PostView.nhn?blogId=youngram2&logNo=220963218066&proxyReferer=https:%2F%2Fwww.google.com%2F
-- ALTER DATABASE DATAFILE '/U01/APP/ORACLE/ORADATA/XE/SYSTEM.DBF' RESIZE 2000M;

-- 작업 저장용 스키마 생성
CREATE TABLESPACE DEV_DAT datafile 'dev_dat.dbf' size 200M;
CREATE TABLESPACE DEV_IDX datafile 'dev_idx.dbf' size 20M;
CREATE USER scott identified by "tiger" DEFAULT TABLESPACE DEV_DAT;
GRANT CONNECT, DBA, RESOURCE TO scott;

-- START DEPARTMENT TABLE
CREATE TABLE SCOTT.DEPARTMENT
(
    DPT_KEY  NUMBER       NOT NULL,
    DPT_NAME VARCHAR2(100) NOT NULL,
    DPT_CODE VARCHAR2(20) NOT NULL
) TABLESPACE DEV_DAT;

CREATE UNIQUE INDEX SCOTT.DPT_PK ON SCOTT.DEPARTMENT (DPT_KEY) TABLESPACE DEV_IDX;
CREATE UNIQUE INDEX SCOTT.DPT_UK_01 ON SCOTT.DEPARTMENT (DPT_CODE) TABLESPACE DEV_IDX;

ALTER TABLE SCOTT.DEPARTMENT ADD (CONSTRAINT DPT_PK PRIMARY KEY (DPT_KEY) USING INDEX SCOTT.DPT_PK);

COMMENT ON TABLE SCOTT.DEPARTMENT IS '부서 테이블';
COMMENT ON COLUMN SCOTT.DEPARTMENT.DPT_KEY IS '부서 키';
COMMENT ON COLUMN SCOTT.DEPARTMENT.DPT_NAME IS '부서 이름';
COMMENT ON COLUMN SCOTT.DEPARTMENT.DPT_CODE IS '부서 코드';

CREATE SEQUENCE SCOTT.SEQ_DPT_KEY
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    NOCACHE
;

INSERT INTO SCOTT.DEPARTMENT(DPT_KEY, DPT_NAME, DPT_CODE) VALUES (SCOTT.SEQ_DPT_KEY.NEXTVAL, '영업', '1234');
INSERT INTO SCOTT.DEPARTMENT(DPT_KEY, DPT_NAME, DPT_CODE) VALUES (SCOTT.SEQ_DPT_KEY.NEXTVAL, '경영지원', '1235');
INSERT INTO SCOTT.DEPARTMENT(DPT_KEY, DPT_NAME, DPT_CODE) VALUES (SCOTT.SEQ_DPT_KEY.NEXTVAL, '개발', '1236');
-- END DEPARTMENT TABLE

-- START EMPLOYEE TABLE
CREATE TABLE SCOTT.EMPLOYEE
(
    EMP_KEY  NUMBER       NOT NULL,
    EMP_NAME VARCHAR2(40) NOT NULL,
    EMP_CODE VARCHAR2(20) NOT NULL,
    DPT_KEY  NUMBER       NOT NULL
) TABLESPACE DEV_DAT;

CREATE UNIQUE INDEX SCOTT.EMP_PK ON SCOTT.EMPLOYEE (EMP_KEY) TABLESPACE DEV_IDX;
CREATE UNIQUE INDEX SCOTT.EMP_UK_01 ON SCOTT.EMPLOYEE (EMP_CODE) TABLESPACE DEV_IDX;

ALTER TABLE SCOTT.EMPLOYEE ADD (CONSTRAINT EMP_PK PRIMARY KEY (EMP_KEY) USING INDEX SCOTT.EMP_PK);
ALTER TABLE SCOTT.EMPLOYEE ADD CONSTRAINT EMP_FK FOREIGN KEY (DPT_KEY) REFERENCES SCOTT.DEPARTMENT (DPT_KEY) ON DELETE CASCADE;

COMMENT ON TABLE SCOTT.EMPLOYEE IS '근무자 테이블';
COMMENT ON COLUMN SCOTT.EMPLOYEE.EMP_KEY IS '근무자 키';
COMMENT ON COLUMN SCOTT.EMPLOYEE.EMP_NAME IS '근무자 이름';
COMMENT ON COLUMN SCOTT.EMPLOYEE.EMP_CODE IS '근무자 코드';
COMMENT ON COLUMN SCOTT.EMPLOYEE.DPT_KEY IS '소속 부서 키';

CREATE SEQUENCE SCOTT.SEQ_EMP_KEY
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    NOCACHE
;

INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '김영업', '4321', 1);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '이영업', '4322', 1);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '오영업', '4323', 1);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '김경영', '4324', 2);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '이경영', '4325', 2);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '김개발', '4326', 3);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '이개발', '4327', 3);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '오개발', '4328', 3);
INSERT INTO SCOTT.EMPLOYEE(EMP_KEY, EMP_NAME, EMP_CODE, DPT_KEY) VALUES (SCOTT.SEQ_EMP_KEY.NEXTVAL, '한개발', '4329', 3);
-- END EMPLOYEE TABLE

-- START STUDENT TABLE
CREATE TABLE SCOTT.STUDENT
(
    STD_KEY  NUMBER       NOT NULL,
    STD_NAME VARCHAR2(50) NOT NULL
) TABLESPACE DEV_DAT;

CREATE UNIQUE INDEX SCOTT.STD_PK ON SCOTT.STUDENT (STD_KEY) TABLESPACE DEV_IDX;

ALTER TABLE SCOTT.STUDENT ADD (CONSTRAINT STD_PK PRIMARY KEY (STD_KEY) USING INDEX SCOTT.STD_PK);

COMMENT ON TABLE SCOTT.STUDENT IS '학생 테이블';
COMMENT ON COLUMN SCOTT.STUDENT.STD_KEY IS '학생 키';
COMMENT ON COLUMN SCOTT.STUDENT.STD_NAME IS '학생 이름';

CREATE SEQUENCE SCOTT.SEQ_STD_KEY
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    NOCACHE
;

INSERT INTO SCOTT.STUDENT(STD_KEY, STD_NAME) VALUES (SCOTT.SEQ_STD_KEY.NEXTVAL, 'A');
INSERT INTO SCOTT.STUDENT(STD_KEY, STD_NAME) VALUES (SCOTT.SEQ_STD_KEY.NEXTVAL, 'B');
INSERT INTO SCOTT.STUDENT(STD_KEY, STD_NAME) VALUES (SCOTT.SEQ_STD_KEY.NEXTVAL, 'C');
INSERT INTO SCOTT.STUDENT(STD_KEY, STD_NAME) VALUES (SCOTT.SEQ_STD_KEY.NEXTVAL, 'D');
-- END STUDENT TABLE

-- START GRADE TABLE
CREATE TABLE SCOTT.GRADE
(
    GRD_KEY   NUMBER       NOT NULL,
    GRD_NAME  VARCHAR2(30) NOT NULL,
    SCORE NUMBER       NOT NULL,
    STD_KEY   NUMBER       NOT NULL
) TABLESPACE DEV_DAT;

CREATE UNIQUE INDEX SCOTT.GRD_PK ON SCOTT.GRADE (GRD_KEY) TABLESPACE DEV_IDX;

ALTER TABLE SCOTT.GRADE ADD (CONSTRAINT GRD_PK PRIMARY KEY (GRD_KEY) USING INDEX SCOTT.GRD_PK);
ALTER TABLE SCOTT.GRADE ADD CONSTRAINT GRD_FK FOREIGN KEY (STD_KEY) REFERENCES SCOTT.STUDENT(STD_KEY) ON DELETE CASCADE;

COMMENT ON TABLE SCOTT.GRADE IS '성적 테이블';
COMMENT ON COLUMN SCOTT.GRADE.GRD_KEY IS '성적 키';
COMMENT ON COLUMN SCOTT.GRADE.GRD_NAME IS '성적 과목 명';
COMMENT ON COLUMN SCOTT.GRADE.SCORE IS '학생 성적';
COMMENT ON COLUMN SCOTT.GRADE.STD_KEY IS '학생 키';

CREATE SEQUENCE SCOTT.SEQ_GRD_KEY
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    NOCACHE
;

INSERT INTO SCOTT.GRADE(GRD_KEY, GRD_NAME, SCORE, STD_KEY) VALUES (SCOTT.SEQ_GRD_KEY.NEXTVAL, '영어', 10, 1);
INSERT INTO SCOTT.GRADE(GRD_KEY, GRD_NAME, SCORE, STD_KEY) VALUES (SCOTT.SEQ_GRD_KEY.NEXTVAL, '영어', 20, 2);
INSERT INTO SCOTT.GRADE(GRD_KEY, GRD_NAME, SCORE, STD_KEY) VALUES (SCOTT.SEQ_GRD_KEY.NEXTVAL, '영어', 40, 4);
-- END GRADE TABLE

-- START EXAM TABLE
CREATE TABLE SCOTT.EXAM
(
    EXM_KEY   NUMBER       NOT NULL,
    EXM_NAME  VARCHAR2(30) NOT NULL,
    MAJOR VARCHAR2(30) NOT NULL,
    SCORE NUMBER       NOT NULL
) TABLESPACE DEV_DAT;

CREATE UNIQUE INDEX SCOTT.EXM_PK ON SCOTT.EXAM (EXM_KEY) TABLESPACE DEV_IDX;

ALTER TABLE SCOTT.EXAM ADD (CONSTRAINT EXM_PK PRIMARY KEY (EXM_KEY) USING INDEX SCOTT.EXM_PK);

CREATE SEQUENCE SCOTT.SEQ_EXM_KEY
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NOCYCLE
    NOCACHE
;

INSERT INTO SCOTT.EXAM(EXM_KEY, EXM_NAME, MAJOR, SCORE) VALUES(SCOTT.SEQ_EXM_KEY.NEXTVAL, '홍길동', '수학', 99);
INSERT INTO SCOTT.EXAM(EXM_KEY, EXM_NAME, MAJOR, SCORE) VALUES(SCOTT.SEQ_EXM_KEY.NEXTVAL, '홍길순', '수학', 95);
INSERT INTO SCOTT.EXAM(EXM_KEY, EXM_NAME, MAJOR, SCORE) VALUES(SCOTT.SEQ_EXM_KEY.NEXTVAL, '고니', '영어', 33);
-- END EXAM TABLE

COMMIT;
